version: 1
datasets:
  - id: eu:flix:gtfs
    format: gtfs
    src: { path: ./dummy-data/gtfs/eu-flix.zip }
#  - id: de:vvs:gtfs
#    format: gtfs
#    license: CC-BY-4.0
#    src:
#      url: https://download.vvs.de/gtfs_realtime.zip
#  - id: de:vbn:gtfs-rt
#    format: gtfs-rt
#    license: CC-BY-SA-4.0
#    src:
#      url: https://gtfsr.vbn.de/gtfsr_connect.bin
#  - id: eu:flix:gtfs
#    format: gtfs
#    src:
#      url: https://gtfs.gis.flix.tech/gtfs_generic_eu.zip
#  - id: google:transitfeed:good_feed
#    format: gtfs
#    src: { path: ./dummy-data/gtfs/good_feed_google-transitfeed.zip }
#  - id: de:gtfs
#    format: gtfs
#    license: CC-BY-4.0
#    src:
#      path: ./dummy-data/gtfs/germany.zip
#  - id: no:gtfs
#    format: gtfs
#    src: { path: ./dummy-data/gtfs/norway.zip }
#  - id: de:bw:gtfs
#    format: gtfs
#    license: DL-DE-BY-2.0
#    src:
#      path: ./dummy-data/gtfs/bw.zip
#  - id: de:vvs:gtfs
#    format: gtfs
#    license: CC-BY-4.0
#    groups: [de:vvs]
#    src:
#      path: ./dummy-data/gtfs/vvs.zip

dataset_groups:
  - id: de:vvs
    consistency:
      stop_ids: true
      stop_coordinates: { radius: 10 }
      trip_ids: { tolerance: 0.2 }
