[package]
name = "drino_server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
routing = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
axum = { workspace = true }
tokio = {workspace = true}